### ISSUE TITLE
errors/not working

### ISSUE THREAD

**Issue by bassman56** [horchi/vdr-plugin-osd2web#3]
Hi
I manually compiled and installed for tumbleweed... , vdr is 2.4.0
when startiing the osd2web pligin I get error messaged

Feb 03 11:39:23 mahrmaid3 vdr[3295]: osd2web: Listener at port (4444) established
Feb 03 11:39:23 mahrmaid3 vdr[3295]: osd2web: using libwebsocket version '3.0.0 unknown-build-hash'
Feb 03 11:39:23 mahrmaid3 vdr[3295]: osd2web: DEBUG: Unhandled 'callbackHttp' got (71)
Feb 03 11:39:23 mahrmaid3 vdr[3295]: osd2web: DEBUG: Unhandled 'callbackOsd2Vdr' got (71)

I can see the page under 127.0.0.1:4444, but there is only the date headline and the button for teh remote, no reaction on button press or SVDRP key press commands, although the ligfile shows that vdr has seen the key.

actually vdr says...
Feb 03 11:11:06 mahrmaid3 vdr[28887]: [28887] ERROR: no OSD provider available - using dummy OSD
same reaction on firefox and midori
So what is wrong? any configuration to change?
Thanks christian
.. PS more errors when pressing keys
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackHttp' got (71)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackOsd2Vdr' got (71)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: localhost/127.0.0.1 'Client disconnected unsolicited' (0x7fbfc000be30)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: localhost/127.0.0.1 'Client disconnected' (0x7fbfc000be30)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackHttp' got (71)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackOsd2Vdr' got (71)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: Client 'localhost/127.0.0.1' connected (0x7fbfc000be30), ping time set to (60)
Feb 03 11:40:26 mahrmaid3 vdr[3362]: osd2web: Error: Ignoring unexpeted client request [{"event":"login","object":{"type":0,"tftprio":100}}B11]
Feb 03 11:40:36 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackHttp' got (71)
Feb 03 11:40:36 mahrmaid3 vdr[3362]: osd2web: DEBUG: Unhandled 'callbackOsd2Vdr' got (71)
ma

**Comment by horchi** [comment]
Hi,

I don't have ported or tested the plugin against libwebsocket 3.x.
Actually it should compatible to libwebsocket form version 2.1.x up to 2.4.x

Best Regards
Jörg

Am 03.02.19 um 11:46 schrieb bassman56:
